In [144]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras import layers, metrics, losses

In [515]:
X,y = make_classification(n_samples=100, n_features=2, n_redundant=0, random_state=42)

In [516]:
X, X_test, y, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [517]:
X_data = tf.data.Dataset.from_tensor_slices(X).batch(16)
y_data = tf.data.Dataset.from_tensor_slices(y).batch(16)
data = tf.data.Dataset.zip((X_data, y_data))

### built-in keras model

In [518]:
model =tf.keras.Sequential()
model.add(layers.Dense(1, input_shape=(2,)))
model.add(layers.Activation(tf.nn.sigmoid))

In [519]:
model.summary()

Model: "sequential_55"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_80 (Dense)             (None, 1)                 3         
_________________________________________________________________
activation_73 (Activation)   (None, 1)                 0         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [520]:
model.input

<tf.Tensor 'dense_80_input:0' shape=(None, 2) dtype=float32>

In [521]:
model.compile(loss=losses.binary_crossentropy, metrics=["accuracy"])

In [524]:
model.fit(X,y, epochs=10, batch_size=16)

Train on 80 samples
Epoch 1/10
80/80 [==============================] - 0s 298us/sample - loss: 1.0905 - accuracy: 0.4000
Epoch 2/10
80/80 [==============================] - 0s 174us/sample - loss: 1.0857 - accuracy: 0.4000
Epoch 3/10
80/80 [==============================] - 0s 152us/sample - loss: 1.0809 - accuracy: 0.4000
Epoch 4/10
80/80 [==============================] - 0s 230us/sample - loss: 1.0762 - accuracy: 0.4000
Epoch 5/10
80/80 [==============================] - 0s 270us/sample - loss: 1.0713 - accuracy: 0.4000
Epoch 6/10
80/80 [==============================] - 0s 268us/sample - loss: 1.0666 - accuracy: 0.4125
Epoch 7/10
80/80 [==============================] - 0s 192us/sample - loss: 1.0617 - accuracy: 0.4125
Epoch 8/10
80/80 [==============================] - 0s 397us/sample - loss: 1.0570 - accuracy: 0.4250
Epoch 9/10
80/80 [==============================] - 0s 287us/sample - loss: 1.0523 - accuracy: 0.4250
Epoch 10/10
80/80 [==============================] - 0s 245us/

In [525]:
model.predict(X)

array([[0.8800186 ],
       [0.549698  ],
       [0.785006  ],
       [0.1833115 ],
       [0.2452526 ],
       [0.8910201 ],
       [0.31538123],
       [0.6776275 ],
       [0.87074286],
       [0.31687728],
       [0.3627581 ],
       [0.8689618 ],
       [0.15098341],
       [0.15089563],
       [0.6378209 ],
       [0.24943331],
       [0.8973662 ],
       [0.61711556],
       [0.29531568],
       [0.71479034],
       [0.75450593],
       [0.14664929],
       [0.3245311 ],
       [0.42136616],
       [0.50786066],
       [0.6530947 ],
       [0.37605837],
       [0.4801928 ],
       [0.3080136 ],
       [0.26759043],
       [0.71887094],
       [0.6811843 ],
       [0.7242301 ],
       [0.7754773 ],
       [0.8479359 ],
       [0.86165786],
       [0.92784965],
       [0.38679603],
       [0.5613064 ],
       [0.77490234],
       [0.16259794],
       [0.51793253],
       [0.28424367],
       [0.21209168],
       [0.49498746],
       [0.6931041 ],
       [0.7376695 ],
       [0.164

In [526]:
optimizer = tf.keras.optimizers.RMSprop()

In [538]:
model =tf.keras.Sequential()
model.add(layers.Dense(1, input_shape=(2,)))
model.add(layers.Activation(tf.nn.relu))
model.add(layers.Dense(12))
model.add(layers.Activation(tf.nn.relu))
model.add(layers.Dense(1))
model.add(layers.Activation(tf.nn.sigmoid))

In [551]:
for epoch in range(100):
    #print("epoch", epoch)
    loss_sum = 0
    N = 0
    for x_batch, y_batch in data:
        
        with tf.GradientTape() as tpe:
            tpe.watch(model.trainable_variables)
            y_pred = model(x_batch, training=True)
            #print(model.trainable_weights)
            loss_sum = tf.reduce_mean(losses.binary_crossentropy(np.expand_dims(y_batch,-1), y_pred, from_logits=True))
            #n = x_batch.shape[0]
            #loss = loss_sum/n
            #N = n + N
            grads = tpe.gradient(loss_sum, model.trainable_variables)
            optimizer.apply_gradients(zip(grads, model.trainable_variables))
    if epoch % 10 == 0:
        print(loss_sum.numpy())
        #print(grads)

0.56971747
0.56213033
0.55508447
0.548448
0.54253495
0.53719985
0.5320817
0.52750957
0.5237171
0.52085793


In [552]:
list(y_data)

[<tf.Tensor: shape=(16,), dtype=int64, numpy=array([0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0])>,
 <tf.Tensor: shape=(16,), dtype=int64, numpy=array([0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0])>,
 <tf.Tensor: shape=(16,), dtype=int64, numpy=array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0])>,
 <tf.Tensor: shape=(16,), dtype=int64, numpy=array([1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1])>,
 <tf.Tensor: shape=(16,), dtype=int64, numpy=array([1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1])>]

In [553]:
res = model.predict(X_test)

In [554]:
preds = np.where(res[:,0]>0.5, 1, 0)

In [555]:
y_test

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0])

In [556]:
preds

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0])